### ISSUE TITLE
openunison-orchestor pod,  custom cpu and memory resources

### ISSUE THREAD

**Issue by fos016** [OpenUnison/helm-charts#125]
Hi

We got serveral oomkilleds in this year. 
Could we set the configuration throught a values file so we don't have to apply a patch the deployment every time we update the chart?

**Comment by mlbiam** [comment]
The capability is already there.  It can be set by adding something similar to your values.yaml:

```yaml
services:
  resources:
    requests:
      memory: 2Gi
    limits:
      memory: 2Gi
```

Then redeploy with ouctl
