### ISSUE TITLE
Kustomize error: Mapping key "securityContext" already defined

### ISSUE THREAD

**Issue by alexhampu** [OpenUnison/helm-charts#138]
I am trying to build the chart with Kustomize, and because in `templates/infrastructure/cronjob.yaml` there is a default `securityContext: {}` defined, and then at the end there is an if else statement with:

```
          {{ if .Capabilities.APIVersions.Has "project.openshift.io/v1/Project" }}
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            runAsNonRoot: true
          {{ else }}
          securityContext:
            fsGroup: 10001
            supplementalGroups: [10001]
            seccompProfile:
              type: RuntimeDefault
            runAsNonRoot: true
            runAsUser: 10001
            runAsGroup: 10001
          {{ end }}
```

When kustomize tries to build the Chart it sees that securityContext is already defined. Is there any reason why the initial `securityContext: {}` is needed, because there is the if else statement, which will always go to else if the condition is not true.

Specific error from kustomize:

```
error: map[string]interface {}(nil): yaml: unmarshal errors:
  line 83: mapping key "securityContext" already defined at line 77
```

If `securityContext: {}` is removed from the `templates/infrastructure/cronjob.yaml` it works fine.
