### ISSUE TITLE
kube-oidc-proxy-openunison failing

### ISSUE THREAD

**Issue by dlorent** [OpenUnison/helm-charts#151]
Similiar to [Issue 43](https://github.com/OpenUnison/openunison-k8s/issues/43) I have been deploying Openunison successfully
on a few clusters - the only thing i know is that the last cluster has been untouched (no manual helm install or anything in the past for testing... ) 

I've tried various ways to sync in different orders or forcing, but im always stuck with the oidc-proxy

```
k logs -n openunison kube-oidc-proxy-openunison-f8f8f594-4b55z
I0424 09:02:12.468040       1 secure_serving.go:213] Serving securely on [::]:8443
I0424 09:02:12.468192       1 dynamic_serving_content.go:132] "Starting controller" name="serving-cert::/etc/oidc/tls/crt.pem::/etc/oidc/tls/key.pem"
I0424 09:02:12.468294       1 tlsconfig.go:240] "Starting DynamicServingCertificateController"
E0424 09:02:12.588561       1 oidc.go:335] oidc authenticator: initializing plugin: 500 Internal Server Error: <?xml version="1.0" encoding="UTF-8" ?>
``` 
which gives following error in ArgoCD
```
one or more objects failed to apply, reason: Internal error occurred: failed calling webhook "applications-openunison.tremolo.io": failed to call webhook: Post "https://openunison-openunison.openunison.svc:443/k8s/webhooks/v1/applications?timeout=30s": dial tcp 10.233.4.150:443: connect: operation not permitted,Internal error occurred: failed calling webhook "authmechs-openunison.tremolo.io": failed to call webhook: Post "https://openunison-openunison.openunison.svc:443/k8s/webhooks/v1/authmechs?timeout=30s": dial tcp 10.233.4.150:443: connect: operation not permitted,Internal error occurred: failed calling webhook "authchains-openunison.tremolo.io": failed to call webhook: Post "https://openunison-openunison.openunison.svc:443/k8s/webhooks/v1/authchains?timeout=30s": dial tcp 10.233.4.150:443: connect: operation not permitted,Internal error occurred: failed calling webhook "workflows-openunison.tremolo.io": failed to call webhook: Post "https://openunison-openunison.openunison.svc:443/k8s/webhooks/v1/workflows?timeout=30s": dial tcp 10.233.4.150:443: connect: operation not permitted,Internal error occurred: failed calling webhook "customazs-openunison.tremolo.io": failed to call webhook: Post "https://openunison-openunison.openunison.svc:443/k8s/webhooks/v1/customazs?timeout=30s": dial tcp 10.233.4.150:443: connect: operation not permitted
```

If i try to sync a second time, it throws
```
one or more objects failed to apply, reason: Internal error occurred: failed calling webhook "authchains-openunison.tremolo.io": failed to call webhook: Post "https://openunison-openunison.openunison.svc:443/k8s/webhooks/v1/authchains?timeout=30s": tls: failed to verify certificate: x509: certificate signed by unknown authority,Internal error occurred: failed calling webhook "workflows-openunison.tremolo.io": failed to call webhook: Post "https://openunison-openunison.openunison.svc:443/k8s/webhooks/v1/workflows?timeout=30s": tls: failed to verify certificate: x509: certificate signed by unknown authority,Internal error occurred: failed calling webhook "customazs-openunison.tremolo.io": failed to call webhook: Post "https://openunison-openunison.openunison.svc:443/k8s/webhooks/v1/customazs?timeout=30s": tls: failed to verify certificate: x509: certificate signed by unknown authority,Internal error occurred: failed calling webhook "applications-openunison.tremolo.io": failed to call webhook: Post "https://openunison-openunison.openunison.svc:443/k8s/webhooks/v1/applications?timeout=30s": tls: failed to verify certificate: x509: certificate signed by unknown authority,Internal error occurred: failed calling webhook "authmechs-openunison.tremolo.io": failed to call webhook: Post "https://openunison-openunison.openunison.svc:443/k8s/webhooks/v1/authmechs?timeout=30s": tls: failed to verify certificate: x509: certificate signed by unknown authority
```
Which as i can read from other posts, are normal since the kube-oidc-proxy isnt running correctly.

Openunison-openunison constantly throws up
```
[2024-04-24 10:00:11,988][XNIO-1 task-1] INFO  AccessLog - [Error] - UNKNOWN - https://127.0.0.1:8443/auth/idp/k8sIdp/.well-known/openid-configuration - cn=none - NONE [127.0.0.1] - [ff60f2b51f5c2ff75fbea42f424712f9fb6f89b7e]
[2024-04-24 10:00:11,988][XNIO-1 task-1] ERROR ConfigSys - Error generated in request
jakarta.servlet.ServletException: Unknown URI : /auth/idp/k8sIdp/.well-known/openid-configuration
        at com.tremolosecurity.proxy.auth.AuthMgrSys.doAuthMgr(AuthMgrSys.java:116) ~[unison-server-core-1.0.40.jar:?]

```

Chart im using
```
apiVersion: v1
name: openunison
description: OpenUnison
version: 1.0.0
# See https://github.com/OpenUnison/helm-charts/blob/master/orchestra-login-portal-argocd/Chart.yaml
dependencies:
  - name: orchestra-login-portal
    version: 2.3.49
    repository: https://nexus.tremolo.io/repository/helm/
  - name: orchestra-login-azuread
    version: 1.0.3
    repository: https://nexus.tremolo.io/repository/helm/

```
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openunison-production
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    cluster: production
    app: openunison
    role: management
spec:
  project: management
  source:
    repoURL: https://dev.azure.com/<redacted>
    targetRevision: HEAD
    path: applications/openunison
    helm:
      releaseName: openunison
      valueFiles:
        - values-production.yaml
  destination:
    server: https://<redacted>:6443
    namespace: openunison
  ignoreDifferences:
    - group: "admissionregistration.k8s.io"
      kind: "ValidatingWebhookConfiguration"
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
        - /webhooks/1/clientConfig/caBundle
        - /webhooks/2/clientConfig/caBundle
        - /webhooks/3/clientConfig/caBundle
        - /webhooks/4/clientConfig/caBundle
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
```

Values

```
orchestra-login-azuread:
  azure:
    uid_attribute_name: oid
    debug: false
    tennant_id: <redacted>
  oidc:
    client_id_is_secret: false
    client_id: "<redacted>"
orchestra-login-portal-argocd:
  oidc:
    client_id: "<redacted>"
  network:
    openunison_host: "<redacted>"
    dashboard_host: "<redacted>"
    api_server_host: "<redacted>"
    session_inactivity_timeout_seconds: 900
    k8s_url: "<redacted>"
    force_redirect_to_tls: false
    createIngressCertificate: false
    ingress_type: nginx
    ingress_annotations:
      cert-manager.io/cluster-issuer: "nginx-http01"
  
  myvd_config_path: "WEB-INF/myvd.conf"
  k8s_cluster_name: ""
  enable_impersonation: true
  impersonation:
    use_jetstack: true
    explicit_certificate_trust: true
  dashboard:
    namespace: "kubernetes-dashboard"
    cert_name: "kubernetes-dashboard-certs"
    label: "k8s-app=kubernetes-dashboard"
    service_name: kubernetes-dashboard
    require_session: true
  certs:
    use_k8s_cm: false
  trusted_certs: []
  monitoring:
    prometheus_service_account: system:serviceaccount:monitoring:prometheus-k
  oidc:
    client_id: ""
    client_id_is_secret: false
    issuer: https://login.microsoftonline.com/<redacted>/v2.0/
    user_in_idtoken: true
    domain: ""
    scopes: openid email profile
    claims:
      sub: upn
      email: email
      given_name: given_name
      family_name: family_name
      display_name: name
      groups: roles
    azure:
      tennant_id: <redacted>
  network_policies:
    enabled: false
    ingress:
      enabled: true
      labels:
        kubernetes.io/metadata.name: ingress-nginx-internet
    monitoring:
      enabled: true
      labels:
        kubernetes.io/metadata.name: monitoring
    apiserver:
      enabled: true
      labels:
        kubernetes.io/metadata.name: kube-syst
  services:
    enable_tokenrequest: false
    token_request_audience: api
    token_request_expiration_seconds: 600
    node_selectors: []
    
  openunison:
    replicas: 1
    non_secret_data:
      K8S_DB_SSO: oidc
      PROMETHEUS_SERVICE_ACCOUNT: system:serviceaccount:monitoring:prometheus-k
    secrets: []
    html:
      prefix: openunison
      image: docker.io/tremolosecurity/openunison-k8s-html
      logosConfigMap: custom-logos
    enable_provisioning: false
    include_auth_chain: azuread-load-groups
```

```
➜  k get secret -n openunison
NAME                       TYPE                DATA   AGE
openunison                 Opqaue              4      24m
openunison-static-keys     Opqaue              2      24m
orchestra-secrets-source   Opaque              4      108m
ou-tls-certificate         kubernetes.io/tls   2      104m
remote-k8s-idp-sig         kubernetes.io/tls   2      24m
unison-saml2-rp-sig        kubernetes.io/tls   2      24m
unison-tls                 kubernetes.io/tls   2      24m

➜  k get cm -n openunison
NAME                DATA   AGE
api-server-config   1      17m
custom-logos        3      24m
kube-root-ca.crt    1      109m
myvd                1      17m
namespace-holder    1      17m
```

```
k get applications.openunison.tremolo.io -n openunison
No resources found in openunison namespace.
```

**Comment by mlbiam** [comment]
The problem is that ArgoCD is syncing the validating wehbhook configuration and overwriting the certificate information set by the operator.  My guess is your `Application` object is missing 

```yaml
ignoreDifferences:
  - group: "admissionregistration.k8s.io"
    kind: "ValidatingWebhookConfiguration"
    jsonPointers:
    - /webhooks/0/clientConfig/caBundle
    - /webhooks/1/clientConfig/caBundle
    - /webhooks/2/clientConfig/caBundle
    - /webhooks/3/clientConfig/caBundle
    - /webhooks/4/clientConfig/caBundle
  syncPolicy:
    syncOptions:
    - RespectIgnoreDifferences=true
```

?  If so, what you'll want to do is:

1. Add an `annotation` to the only `OpenUnison` object in the `openunison` namespace (it's `openunison-orchestra` in generic helm deployments) - This will trigger the operator to overwrite the `caBundle` with the correct certificate
2. update your ArgoCD `Application` object with the above yaml to ignore those differences so that ArgoCD doesn't try to overwrite it again.
