### ISSUE TITLE
kustomize fails because of duplicate securityContext in cronJob

### ISSUE THREAD

**Issue by fbuchmeier-abi** [OpenUnison/helm-charts#152]
Hi!

I am using the helm chart with a kustomize post-renderer and the installation currently fails because there is a duplicate key `securitContext` in the cronjob template:

```
  - 'Error: map[string]interface {}(nil): yaml: unmarshal errors:'
  - '  line 84: mapping key "securityContext" already defined at line 78'
  - ': exit status 1'
  - ''
  - Use --debug flag to render out invalid YAML
```

```
 helm template orchestra tremolo/orchestra  --show-only templates/infrastructure/cronjob.yaml | grep securityContext -A3 -B3
            - /var/run/secrets/kubernetes.io/serviceaccount/token
            - /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            - "2,3,4,5,6"
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
--
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          serviceAccount: openunison-operator
          serviceAccountName: openunison-operator
          terminationGracePeriodSeconds: 30
--
          securityContext:
            fsGroup: 10001
            supplementalGroups: [10001]
            seccompProfile:
```

There is an securityContext defined in:  https://github.com/OpenUnison/helm-charts/blob/master/orchestra/templates/infrastructure/cronjob.yaml#L107 as well as in https://github.com/OpenUnison/helm-charts/blob/master/orchestra/templates/infrastructure/cronjob.yaml#L139 or in https://github.com/OpenUnison/helm-charts/blob/master/orchestra/templates/infrastructure/cronjob.yaml#L144

I'll create a PR in a moment to fix this as it is only a one liner.

Best regards,
Florian.
