### ISSUE TITLE
Inconsistent naming of multi-cluster buttons for Kubernetes Dashboard and Kubernetes Tokens

### ISSUE THREAD

**Issue by spantaleev** [OpenUnison/helm-charts#197]
I have a `main` cluster and two other satellite clusters (`ni` & `san`).

I'd like to link these to the `main` OpenUnison's console.

For the `main` cluster, I'm using configuration like this:

```yml
non_secret_data:
  SHOW_PORTAL_ORGS: "true"
  K8S_DEPLOYMENT_NAME: "main"
  K8S_DEPLOYMENT_DESC: "Current cluster (main)"
```

For the others, I'm using the `openunison-k8s-add-cluster` Helm Chart with values like this:

```yml
cluster:
  name: "ni"
  label: "ni"
  description: "Remote cluster (ni)"
  sso:
    enabled: false
    inactivityTimeoutSeconds: 900
  hosts:
    portal: "some-hostname"
    dashboard: "another-hostname}"
  az_groups: [...]
```

This gives me the most consistent look I could achieve, but it's still inconsistent in that:

- buttons for the `main cluster` are called: **Kubernetes Dashboard** and **Kubernetes Tokens**. The relevant code is [here](https://github.com/OpenUnison/helm-charts/blob/33d7b621dc2d98e516a435a2ea66afbda4b52b7b/orchestra-login-portal/templates/openunison/urls/portal-urls.yaml#L17) and [here](https://github.com/OpenUnison/helm-charts/blob/33d7b621dc2d98e516a435a2ea66afbda4b52b7b/orchestra-login-portal/templates/openunison/urls/portal-urls.yaml#L64)

    ![Image](https://github.com/user-attachments/assets/9ccf311a-b6ad-47af-b9e8-9e0a47e76e4f)

- buttons for the satellite clusters (e.g. `ni`) are called: **ni Dashboard** and **ni Tokens**. The relevant code is [here](https://github.com/OpenUnison/helm-charts/blob/33d7b621dc2d98e516a435a2ea66afbda4b52b7b/openunison-k8s-add-cluster/templates/urls/dashboard.yaml#L8) and [here](https://github.com/OpenUnison/helm-charts/blob/33d7b621dc2d98e516a435a2ea66afbda4b52b7b/openunison-k8s-add-cluster/templates/urls/tokens.yaml#L8)

    ![Image](https://github.com/user-attachments/assets/ade79953-148e-451c-9552-cfde5ef857a5)

---------------------

It'd be nice to allow these labels to be customizable, but even if they are, it'd be great if they can be consistent by default.

![Image](https://github.com/user-attachments/assets/47efe96c-832e-421c-bb05-08b23447f86b)

Given that the cluster label is already visible in the cluster picker (above the buttons), there's probably no need to repeat it in the button label. Buttons could become just **Kubernetes Dashboard** and it'd still be obvious which cluster they pertain to.

This is probably the simplest fix as well, but let me know if I'm missing something.
