### ISSUE TITLE
Add support for ingressClassName in helm chart

### ISSUE THREAD

**Issue by mydompp** [OpenUnison/helm-charts#94]
OpenUnison doesn't forward request after authorization when ingressClass not equal default in k8s. 
Also, kubernetes.io/ingress.class annotation is progressively replaced with ingressClassName in the ingress as of v1.18
I suggest adding  ingressClassName variabe and propagate to all ingresses templates for orchestra.

**Comment by mlbiam** [comment]
> OpenUnison doesn't forward request after authorization when ingressClass not equal default in k8s.

Not sure what you mean.  You can specify a "simple" `Ingress` for `network.ingress_type` and then configure the `Ingress` based on the annotations for which ever ingress you wish if it's not directly supported by the helm charts.

> I suggest adding ingressClassName variabe and propagate to all ingresses templates for orchestra.
agreed.  stay tuned

**Comment by mydompp** [comment]
Hi, my part of config
`ingress_type: nginx`
I don't want to use deprecated annotation [https://kubernetes.io/docs/concepts/services-networking/ingress/#deprecated-annotation](url)  kubernetes.io/ingress.class
I have some ingress classes in my cluster and class for openUnison is not default
````
kubectl get ingressclass
NAME                      CONTROLLER                       PARAMETERS   AGE
alb                       ingress.k8s.aws/alb              <none>       60d
openunison-nginx-dev      k8s.io/openunison-nginx-dev      <none>       42h
````
I should add  `ingressClassName: openunison-nginx-dev`  to ingress scec.

````
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "20"
    kubernetes.io/ingress.class: nginx
    meta.helm.sh/release-name: orchestra
    meta.helm.sh/release-namespace: openunison
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/backend-protocol: https
    nginx.ingress.kubernetes.io/proxy-read-timeout: "86400"
    nginx.ingress.kubernetes.io/secure-backends: "true"
    nginx.ingress.kubernetes.io/session-cookie-hash: sha1
    nginx.ingress.kubernetes.io/session-cookie-name: openunison-orchestra
    nginx.org/ssl-services: openunison-orchestra
  generation: 4
  labels:
    app.kubernetes.io/component: ingress-nginx
    app.kubernetes.io/instance: openunison-orchestra
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: openunison
    app.kubernetes.io/part-of: openunison
  name: openunison-orchestra
  namespace: openunison
spec:
  ingressClassName: openunison-nginx-dev
  ````
So I suggest extending value `network.ingress_class_name` and add smth like 
````
spec:
  {{- if .Values.network.ingress_class_name }}
  ingressClassName: {{ .Values.network.ingress_class_name }}
  {{- end }}
````
to all ingress templates ingress-simple.yaml, nginx.yaml and traefik.yaml
WDYT?
